apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/inspektor-gadget/inspektor-gadget
      ref: main
    includePaths:
    - charts/gadget/**/*
- path: helm/inspektor-gadget/templates
  contents:
  - path: .
    directory:
      path: vendor/charts/gadget/templates
