apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if not .Values.skipLabels }}
  labels:
    {{- include "gadget.labels" . | nindent 4 }}
  {{- end }}
  name: {{ include "gadget.fullname" . }}
  namespace: {{ include "gadget.namespace" . }}
